version: '3'
vars:
  DOCKER_IMAGE: ghcr.io/codeteam2-dev/echo:latest
tasks:
  build:
    cmds:
    - docker build -t {{ .DOCKER_IMAGE }} -f Dockerfile .
  run:
    cmds:
    - docker run -it --rm {{ .DOCKER_IMAGE }}
  publish:
    cmds:
    - docker push {{ .DOCKER_IMAGE }}
