version: '3'
vars:
  DOCKER_IMAGE: ghcr.io/codeteam2-dev/echo:latest
tasks:
  setup:
    cmds:
    - brew install goreleaser/tap/goreleaser
    - brew install ko
  build:
    cmds:
    - goreleaser build -f .goreleaser.yaml
  run:
    cmds:
    - docker run -it --rm {{ .DOCKER_IMAGE }}
  release:
    cmds:
    - goreleaser release -f .goreleaser.yaml